server:
  port: 9081

spring:
  config:
    import: 
      - nacos:${spring.cloud.nacos.discovery.service}.${spring.cloud.nacos.config.file-extension}
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.75.1:8848
        metadata:
          my-key: my-meta-value
        service: teacher
        username: nacos
        password: nacos
        port: 9081
        weight: 1
        ephemeral: true
      config:
        server-addr: 192.168.75.1:8848
        file-extension: yml
        username: nacos
        password: nacos